In [17]:
import pandas as pd
dataset=pd.read_csv('moisture-sensor.csv')

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Id        150 non-null    int64 
 1   Moisture  150 non-null    int64 
 2   State     150 non-null    object
 3   Action    150 non-null    object
dtypes: int64(2), object(2)
memory usage: 4.8+ KB


In [19]:
dataset

Id  Moisture State     Action
0      0      1669   wet  motor off
1      1      1675   wet  motor off
2      2      1680   wet  motor off
3      3      1686   wet  motor off
4      4      1663   wet  motor off
..   ...       ...   ...        ...
145  145      1803   wet  motor off
146  146      1982   wet  motor off
147  147      1574   wet  motor off
148  148      3146   dry   motor on
149  149      1269   wet  motor off

[150 rows x 4 columns]

In [20]:
X=dataset.iloc[:,1]

In [21]:
X

0      1669
1      1675
2      1680
3      1686
4      1663
       ... 
145    1803
146    1982
147    1574
148    3146
149    1269
Name: Moisture, Length: 150, dtype: int64

In [22]:
X = dataset.iloc[:, 1].values.reshape(-1, 1)

In [23]:
X

array([[1669],
       [1675],
       [1680],
       [1686],
       [1663],
       [1665],
       [1104],
       [1062],
       [4095],
       [1023],
       [ 959],
       [ 927],
       [4095],
       [ 989],
       [ 963],
       [ 944],
       [1127],
       [1035],
       [1062],
       [1130],
       [ 990],
       [ 915],
       [1069],
       [1021],
       [1322],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [3601],
       [1781],
       [ 855],
       [ 895],
       [3162],
       [3119],
       [2189],
       [3071],
       [1155],
       [2163],
       [1449],
       [3099],
       [1059],
       [1045],
       [3101],
       [1940],
       [1190],
       [1195],
       [1200],
       [1193],
       [1215],
       [1274],
       [1088],
       [1142],
       [1162],
       [1185],
       [1185],
       [1199],
       [1200],
       [1205],
       [1197],
       [11

In [24]:
y = dataset.iloc[:, 1].values

In [25]:
y

array([1669, 1675, 1680, 1686, 1663, 1665, 1104, 1062, 4095, 1023,  959,
        927, 4095,  989,  963,  944, 1127, 1035, 1062, 1130,  990,  915,
       1069, 1021, 1322, 4095, 4095, 4095, 4095, 4095, 4095, 4095, 4095,
       4095, 4095, 3601, 1781,  855,  895, 3162, 3119, 2189, 3071, 1155,
       2163, 1449, 3099, 1059, 1045, 3101, 1940, 1190, 1195, 1200, 1193,
       1215, 1274, 1088, 1142, 1162, 1185, 1185, 1199, 1200, 1205, 1197,
       1198, 1183, 1195, 1207, 1214, 1222, 1220, 1218, 1213, 1189, 1183,
       1205, 3105, 3066, 3070, 1843,  976, 3043, 1709, 1008, 1705, 1207,
       1518, 2032, 1613, 2992, 2986, 2976, 1949,  947, 1251, 2980, 1167,
       3013, 1974, 2234, 1390, 3039, 3024, 3011, 1265, 1327, 1360, 1168,
       1149, 1168, 1179, 1104,  979, 1003, 1473, 1275, 1162, 1058, 1039,
       1413, 1018,  954, 1013, 2933, 1831, 2550, 3067, 1391, 1040, 1274,
       1101, 1072, 1095, 1093, 1141, 1200, 1197, 1093, 1103, 1002, 1518,
       1018, 1090, 1803, 1982, 1574, 3146, 1269])

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [27]:
from sklearn.neighbors import KNeighborsClassifier
ai = KNeighborsClassifier(n_neighbors=3)
ai.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [28]:
ai.predict([[100]])

array([855])

In [29]:
y_ai=ai.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score

y_ai = ai.predict(X_test)
accuracy = accuracy_score(y_test, y_ai)
print(f"Accuracy: {accuracy}")

Accuracy: 0.0*100


import  pickle
with open('ai.pkl','wb') as f:
    pickle.dump(ai,f)